name: Print Job Summary
on:
  push:
    branches:
      - '**'
permissions:
  contents: read
  id-token: write
jobs:
  JFrog-Job-Summary:
    strategy:
      matrix:
        os: [ ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JFROG_CLI_LOG_LEVEL: DEBUG
        with:
          custom-server-id: my-server

      - name: rt ping
        run: |
          jf rt ping --server-id test1
          
      - name: Setup JFrog CLI2
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JFROG_CLI_LOG_LEVEL: DEBUG
        with:
          custom-server-id: my-server2

      - name: rt ping
        run: |
          jf rt ping
