name: Print Job Summary
on:
  push:
    branches:
      - '**'
permissions:
  contents: read
  id-token: write
jobs:
  JFrog-Job-Summary:
    strategy:
      matrix:
        os: [ ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JFROG_CLI_LOG_LEVEL: DEBUG
        # with:
        #   download-repository: generic-local-eyal
        #   version: 2.67.0

      - name: rt ping
        run: |
          jf rt ping

      # - name: Publish build info
      #   run: |
      #     jf rt bce
