name: Print Job Summary
on:
  push:
    branches:
      - '**'
jobs:
  JFrog-Job-Summary:
    strategy:
      matrix:
        os: [ ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: eyaldelarea/setup-jfrog-cli@fix-github-onprem
        env:
          JF_URL: ${{  secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_PROJECT: "jobsummary"

      - name: Run publish
        run: |
          jf rt bp firstBuild 123

      - name: Run Upload
        run: jf rt upload --spec=./testdata/filespecs/github_job_summaries.json