name: Print Job Summary
on:
  push:
    branches:
      - '**'
jobs:
  JFrog-Job-Summary:
    strategy:
      matrix:
        os: [ ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JFROG_CLI_LOG_LEVEL: DEBUG
        with:
          oidc-provider-name: setup-jfrog-cli-test

      - name: rt ping
        run: |
          jf rt ping

      - name: Publish build info
        run: |
          jf rt bce
