name: Print Job Summary
on:
  push:
    branches:
      - '**'
env:
  # Defined at top level as we use local CLI for testings
  JFROG_CLI_LOG_LEVEL: DEBUG
  JF_URL: ${{  vars.JF_URL }}
  JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
  JF_PROJECT: "jobsummary"
jobs:
  Test-GitHub-Job-Summary:
    strategy:
      matrix:
        os: [ ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false
      # Build the current CLI to verify no failures
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "eyaldelarea/jfrog-cli"
          ref: "job_summaries"
      - name: Build current CLI
        run: go build .

      - uses: eyaldelarea/setup-jfrog-cli@cleanUpSummaries
        env:
          JF_PROJECT: "jobsummary"
          JF_URL: ${{  vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Run dry run upload
        run: ./jfrog-cli rt upload --spec=./testdata/filespecs/github_job_summaries.json

      - name: Run publish
        run: ./jfrog-cli rt bp firstBuild 123

      - name: Run scan
        run: ./jfrog-cli scan ./testdata/scanSummaryTests/fileOne.rpm && ./jfrog-cli scan ./testdata/scanSummaryTests/fileTwo.jar

      - name: Run scan
        run: ./jfrog-cli build-scan firstBuild 123
