name: NuGet Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  # Triggers the workflow on labeled PRs only.
  pull_request_target:
    types: [ labeled ]

# Ensures that only the latest commit is running for each PR at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  NuGet-Tests:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'push'
    name: NuGet tests (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Ubuntu agents require Mono to run nuget.exe.
      # Also, there is an issue with the .NET setup action that requires setting permissions for the dotnet home directory.
      # Therefore, we manually set permissions until the issue is resolved. (https://github.com/actions/setup-dotnet/issues/565)
      - name: Prepare Ubuntu agent
        if: matrix.os == 'ubuntu'
        run: |
          # Install Mono
          sudo apt-get update
          sudo apt-get install -y apt-transport-https dirmngr gnupg ca-certificates
          sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt-get update
          sudo apt-get install -y mono-complete
          # Set permissions for the dotnet home directory
          sudo mkdir -p /usr/share/dotnet
          sudo chmod 777 /usr/share/dotnet

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Install NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: '6.x'

      - name: Setup Go with cache
        uses: jfrog/.github/actions/install-go-with-cache@main

      - name: Install local Artifactory
        uses: jfrog/.github/actions/install-local-artifactory@main
        with:
          RTLIC: ${{ secrets.RTLIC }}

      - name: Run NuGet tests
        run: go test -v github.com/jfrog/jfrog-cli --timeout 0 --test.nuget
